use_frameworks!

source 'git@code.aliyun.com:szfy_ios/SZFYSpecs.git'

target 'URLRouter_Example' do
  pod 'URLRouter', :path => '../'

  target 'URLRouter_Tests' do
    inherit! :search_paths

    
  end
end
